const menu = [
    {
        id: 1,
        title: "Peperoni und Oliven",
        category: "Kalte Vorspeisen",
        price: "4,80",
        img: "",
        desc: "",
    },
    {
        id: 2,
        title: "Zaziki",
        category: "Kalte Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Joghurt mit Gurken und Knoblauch",
    },
    {
        id: 3,
        title: "Tamaras",
        category: "Kalte Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Kaviarcreme",
    },
    {
        id: 4,
        title: "Oktopus Salat",
        category: "Kalte Vorspeisen",
        price: "10,90",
        img: "",
        desc: "Eingelegt in Essig und Öl",
    },
    {
        id: 5,
        title: "Feta",
        category: "Kalte Vorspeisen",
        price: "7,30",
        img: "",
        desc: "Schafskäse natur, mit Olivenöl",
    },
    {
        id: 6,
        title: "Kalamares Salat",
        category: "Kalte Vorspeisen",
        price: "10,90",
        img: "",
        desc: "Eingelegt in Essig und Öl",
    },
    {
        id: 7,
        title: "Pfahlmuscheln",
        category: "Warme Vorspeisen",
        price: "8,70",
        img: "",
        desc: "Überbacken, in pikanter Tomatensoße mit Knoblauch und Käse",
    },
    {
        id: 8,
        title: "Dolmadakia",
        category: "Warme Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Weinblätter gefüllt mit Reis",
    },
    {
        id: 9,
        title: "Saganaki",
        category: "Warme Vorspeisen",
        price: "7,90",
        img: "",
        desc: "Gebratener Käse in Eiermehlteig",
    },
    {
        id: 10,
        title: "Gebratene Aubergine",
        category: "Warme Vorspeisen",
        price: "7,80",
        img: "",
        desc: "mit Zaziki",
    },
    {
        id: 11,
        title: "Gebratene Paprika",
        category: "Warme Vorspeisen",
        price: "7,90",
        img: "",
        desc: "mit Zaziki",
    },
    {
        id: 12,
        title: "Oktapus pikant",
        category: "Warme Vorspeisen",
        price: "8,90",
        img: "",
        desc: "Überbacken, in pikanter Tomatensoße mit Knoblauch und Käse",
    },
    {
        id: 13,
        title: "Vorspeisenplatte",
        category: "Warme Vorspeisen",
        price: "13,40",
        img: "",
        desc: "Für 1 Person | Peperoni, Oliven, Zaziki, Tamaras, Oktapus und Calamares Salat, Dolmadakia",
    },
    {
        id: 15,
        title: "Sorbas-Platte",
        category: "Warme Vorspeisen",
        price: "11,50",
        img: "",
        desc: "Für 1 Person | Zaziki, Saganaki, Gebratene Auberginen und Paprika",
    },
    {
        id: 17,
        title: "Feta spezial",
        category: "Warme Vorspeisen",
        price: "9,30",
        img: "",
        desc: "Schafskäse natur, überbacken mit Olivenöl, leicht pikant",
    },
    {
        id: 18,
        title: "Tomatensuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 19,
        title: "Gulaschsuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 20,
        title: "Hühnersuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 21,
        title: "Bohnensuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 22,
        title: "Tomaten Salat",
        category: "Salat",
        price: "4,00",
        img: "",
        desc: "",
    },
    {
        id: 23,
        title: "Bauern Salat",
        category: "Salat",
        price: "6,50",
        img: "",
        desc: "Klein | Tomaten, Krautsalat, Gurken, Oliven, Peperoni, Zwiebeln, Schafskäse",
    },
    {
        id: 24,
        title: "Bauern Salat",
        category: "Salat",
        price: "12,90",
        img: "",
        desc: "Groß | Tomaten, Krautsalat, Gurken, Oliven, Peperoni, Zwiebeln, Schafskäse",
    },
    {
        id: 25,
        title: "Athen Salat",
        category: "Salat",
        price: "10,90",
        img: "",
        desc: "Eisbergsalat, Tomaten, Gurken, Mais, Schinken, Käse, Kraut, Ei und Sauce",
    },
    {
        id: 26,
        title: "Hellas Salat",
        category: "Salat",
        price: "11,30",
        img: "",
        desc: "Eisbergsalat, Tomaten, Gurken, Thunfisch, Krabben, Käse, Ei, Zwiebeln",
    },
    {
        id: 29,
        title: "Krautsalat",
        category: "Salat",
        price: "3,50",
        img: "",
        desc: "",
    },
    {
        id: 30,
        title: "Gemischter Salat",
        category: "Salat",
        price: "3,50",
        img: "",
        desc: "",
    },
    {
        id: 31,
        title: "Gegrillte Peperoni",
        category: "Salat",
        price: "6,60",
        img: "",
        desc: "Mit Knoblauchcreme und Brot",
    },
    {
        id: 33,
        title: "Meteora Teller",
        category: "Spezialitäten vom Grill",
        price: "15,50",
        img: "",
        desc: "Gyros, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 34,
        title: "Santorini Teller",
        category: "Spezialitäten vom Grill",
        price: "15,90",
        img: "",
        desc: "1 Souvlaki, 1 Leber mit Reis, Zaziki und Salat",
    },
    {
        id: 35,
        title: "Gyros",
        category: "Spezialitäten vom Grill",
        price: "14,20",
        img: "",
        desc: "Mit Reis, Zaziki und Salat",
    },
    {
        id: 36,
        title: "Souvlaki",
        category: "Spezialitäten vom Grill",
        price: "14,40",
        img: "",
        desc: "2 Fleischspieße mit Reis und Salat",
    },
    {
        id: 37,
        title: "Artemis Teller",
        category: "Spezialitäten vom Grill",
        price: "14,70",
        img: "",
        desc: "Gyros, 2 Leber mit Reis, Zaziki und Salat",
    },
    {
        id: 38,
        title: "Athen Teller",
        category: "Spezialitäten vom Grill",
        price: "20,90",
        img: "",
        desc: "Gyros, 1 Souvlaki, 1 Leber, 1 Bifteki, 1 Lammkotelett mit Reis, Zaziki und Salat",
    },
    {
        id: 39,
        title: "Zeus Teller",
        category: "Spezialitäten vom Grill",
        price: "17,60",
        img: "",
        desc: "1 Hähnchenbrust, 1 Rumpsteak 100g, mit Reis und Salat",
    },
    {
        id: 40,
        title: "Korfu Teller",
        category: "Spezialitäten vom Grill",
        price: "18,90",
        img: "",
        desc: "1 Rumpsteak 100g, 1 Spieß, Gyros mit Reis, Zaziki und Salat",
    },
    {
        id: 41,
        title: "Ares Teller",
        category: "Spezialitäten vom Grill",
        price: "17,20",
        img: "",
        desc: "Gyros, 2 Lammkotelett mit Reis, Zaziki und Salat",
    },
    {
        id: 42,
        title: "Poseidon Teller",
        category: "Spezialitäten vom Grill",
        price: "16,90",
        img: "",
        desc: "2 Souvlaki, 1 Lammkotelett mit Reis und Salat",
    },
    {
        id: 43,
        title: "Apollon Teller",
        category: "Spezialitäten vom Grill",
        price: "16,40",
        img: "",
        desc: "Gyros, 1 Souvlaki mit Reis, Zaziki und Salat",
    },
    {
        id: 44,
        title: "Hermes Teller",
        category: "Spezialitäten vom Grill",
        price: "18,20",
        img: "",
        desc: "Gyros, 1 Souvlaki, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 45,
        title: "Schweineleber",
        category: "Spezialitäten vom Grill",
        price: "13,90",
        img: "",
        desc: "Mit Zwiebeln, Zaziki, Reis und Salat",
    },
    {
        id: 46,
        title: "Antonis Teller",
        category: "Spezialitäten vom Grill",
        price: "21,40",
        img: "",
        desc: "2 Lammkotelett, 2 Bifteki, 2 Leber, 1 Steak mit Reis und Salat",
    },
    {
        id: 47,
        title: "Trikala Teller",
        category: "Spezialitäten vom Grill",
        price: "20,10",
        img: "",
        desc: "Gyros, 1 Souvlaki, 2 Leber, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 48,
        title: "Schweinefilet",
        category: "Spezialitäten vom Grill",
        price: "19,10",
        img: "",
        desc: "Mit Käsesauce, Pommes Frites und Salat",
    },
    {
        id: 49,
        title: "Spezial Bifteki",
        category: "Spezialitäten vom Grill",
        price: "17,60",
        img: "",
        desc: "Hacksteak mit Schafskäse gefüllt, mit Reis und Salat",
    },
    {
        id: 50,
        title: "Syrtaki Teller",
        category: "Spezialitäten vom Grill",
        price: "18,10",
        img: "",
        desc: "1 Souvlaki, 1 Schweinesteak, Gyros mit Reis, Zaziki und Salat",
    }
    ]
export default menu