const menu = [
    {
        id: 1,
        title: "Peperoni und Oliven",
        category: "Kalte Vorspeisen",
        price: "4,80",
        img: "",
        desc: "",
    },
    {
        id: 2,
        title: "Zaziki",
        category: "Kalte Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Joghurt mit Gurken und Knoblauch",
    },
    {
        id: 3,
        title: "Tamaras",
        category: "Kalte Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Kaviarcreme",
    },
    {
        id: 4,
        title: "Oktopus Salat",
        category: "Kalte Vorspeisen",
        price: "10,90",
        img: "",
        desc: "Eingelegt in Essig und Öl",
    },
    {
        id: 5,
        title: "Feta",
        category: "Kalte Vorspeisen",
        price: "7,30",
        img: "",
        desc: "Schafskäse natur, mit Olivenöl",
    },
    {
        id: 6,
        title: "Kalamares Salat",
        category: "Kalte Vorspeisen",
        price: "10,90",
        img: "",
        desc: "Eingelegt in Essig und Öl",
    },
    {
        id: 7,
        title: "Pfahlmuscheln",
        category: "Warme Vorspeisen",
        price: "8,70",
        img: "",
        desc: "Überbacken, in pikanter Tomatensoße mit Knoblauch und Käse",
    },
    {
        id: 8,
        title: "Dolmadakia",
        category: "Warme Vorspeisen",
        price: "4,90",
        img: "",
        desc: "Weinblätter gefüllt mit Reis",
    },
    {
        id: 9,
        title: "Saganaki",
        category: "Warme Vorspeisen",
        price: "7,90",
        img: "",
        desc: "Gebratener Käse in Eiermehlteig",
    },
    {
        id: 10,
        title: "Gebratene Aubergine",
        category: "Warme Vorspeisen",
        price: "7,80",
        img: "",
        desc: "mit Zaziki",
    },
    {
        id: 11,
        title: "Gebratene Paprika",
        category: "Warme Vorspeisen",
        price: "7,90",
        img: "",
        desc: "mit Zaziki",
    },
    {
        id: 12,
        title: "Oktapus pikant",
        category: "Warme Vorspeisen",
        price: "8,90",
        img: "",
        desc: "Überbacken, in pikanter Tomatensoße mit Knoblauch und Käse",
    },
    {
        id: 13,
        title: "Vorspeisenplatte",
        category: "Warme Vorspeisen",
        price: "13,40",
        img: "",
        desc: "Für 1 Person | Peperoni, Oliven, Zaziki, Tamaras, Oktapus und Calamares Salat, Dolmadakia",
    },
    {
        id: 15,
        title: "Sorbas-Platte",
        category: "Warme Vorspeisen",
        price: "11,50",
        img: "",
        desc: "Für 1 Person | Zaziki, Saganaki, Gebratene Auberginen und Paprika",
    },
    {
        id: 17,
        title: "Feta spezial",
        category: "Warme Vorspeisen",
        price: "9,30",
        img: "",
        desc: "Schafskäse natur, überbacken mit Olivenöl, leicht pikant",
    },
    {
        id: 18,
        title: "Tomatensuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 19,
        title: "Gulaschsuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 20,
        title: "Hühnersuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 21,
        title: "Bohnensuppe",
        category: "Suppen",
        price: "4,50",
        img: "",
        desc: "",
    },
    {
        id: 22,
        title: "Tomaten Salat",
        category: "Salat",
        price: "4,00",
        img: "",
        desc: "",
    },
    {
        id: 23,
        title: "Bauern Salat",
        category: "Salat",
        price: "6,50",
        img: "",
        desc: "Klein | Tomaten, Krautsalat, Gurken, Oliven, Peperoni, Zwiebeln, Schafskäse",
    },
    {
        id: 24,
        title: "Bauern Salat",
        category: "Salat",
        price: "12,90",
        img: "",
        desc: "Groß | Tomaten, Krautsalat, Gurken, Oliven, Peperoni, Zwiebeln, Schafskäse",
    },
    {
        id: 25,
        title: "Athen Salat",
        category: "Salat",
        price: "10,90",
        img: "",
        desc: "Eisbergsalat, Tomaten, Gurken, Mais, Schinken, Käse, Kraut, Ei und Sauce",
    },
    {
        id: 26,
        title: "Hellas Salat",
        category: "Salat",
        price: "11,30",
        img: "",
        desc: "Eisbergsalat, Tomaten, Gurken, Thunfisch, Krabben, Käse, Ei, Zwiebeln",
    },
    {
        id: 29,
        title: "Krautsalat",
        category: "Salat",
        price: "3,50",
        img: "",
        desc: "",
    },
    {
        id: 30,
        title: "Gemischter Salat",
        category: "Salat",
        price: "3,50",
        img: "",
        desc: "",
    },
    {
        id: 31,
        title: "Gegrillte Peperoni",
        category: "Salat",
        price: "6,60",
        img: "",
        desc: "Mit Knoblauchcreme und Brot",
    },
    {
        id: 33,
        title: "Meteora Teller",
        category: "Spezialitäten vom Grill",
        price: "15,50",
        img: "",
        desc: "Gyros, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 34,
        title: "Santorini Teller",
        category: "Spezialitäten vom Grill",
        price: "15,90",
        img: "",
        desc: "1 Souvlaki, 1 Leber mit Reis, Zaziki und Salat",
    },
    {
        id: 35,
        title: "Gyros",
        category: "Spezialitäten vom Grill",
        price: "14,20",
        img: "",
        desc: "Mit Reis, Zaziki und Salat",
    },
    {
        id: 36,
        title: "Souvlaki",
        category: "Spezialitäten vom Grill",
        price: "14,40",
        img: "",
        desc: "2 Fleischspieße mit Reis und Salat",
    },
    {
        id: 37,
        title: "Artemis Teller",
        category: "Spezialitäten vom Grill",
        price: "14,70",
        img: "",
        desc: "Gyros, 2 Leber mit Reis, Zaziki und Salat",
    },
    {
        id: 38,
        title: "Athen Teller",
        category: "Spezialitäten vom Grill",
        price: "20,90",
        img: "",
        desc: "Gyros, 1 Souvlaki, 1 Leber, 1 Bifteki, 1 Lammkotelett mit Reis, Zaziki und Salat",
    },
    {
        id: 39,
        title: "Zeus Teller",
        category: "Spezialitäten vom Grill",
        price: "17,60",
        img: "",
        desc: "1 Hähnchenbrust, 1 Rumpsteak 100g, mit Reis und Salat",
    },
    {
        id: 40,
        title: "Korfu Teller",
        category: "Spezialitäten vom Grill",
        price: "18,90",
        img: "",
        desc: "1 Rumpsteak 100g, 1 Spieß, Gyros mit Reis, Zaziki und Salat",
    },
    {
        id: 41,
        title: "Ares Teller",
        category: "Spezialitäten vom Grill",
        price: "17,20",
        img: "",
        desc: "Gyros, 2 Lammkotelett mit Reis, Zaziki und Salat",
    },
    {
        id: 42,
        title: "Poseidon Teller",
        category: "Spezialitäten vom Grill",
        price: "16,90",
        img: "",
        desc: "2 Souvlaki, 1 Lammkotelett mit Reis und Salat",
    },
    {
        id: 43,
        title: "Apollon Teller",
        category: "Spezialitäten vom Grill",
        price: "16,40",
        img: "",
        desc: "Gyros, 1 Souvlaki mit Reis, Zaziki und Salat",
    },
    {
        id: 44,
        title: "Hermes Teller",
        category: "Spezialitäten vom Grill",
        price: "18,20",
        img: "",
        desc: "Gyros, 1 Souvlaki, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 45,
        title: "Schweineleber",
        category: "Spezialitäten vom Grill",
        price: "13,90",
        img: "",
        desc: "Mit Zwiebeln, Zaziki, Reis und Salat",
    },
    {
        id: 46,
        title: "Antonis Teller",
        category: "Spezialitäten vom Grill",
        price: "21,40",
        img: "",
        desc: "2 Lammkotelett, 2 Bifteki, 2 Leber, 1 Steak mit Reis und Salat",
    },
    {
        id: 47,
        title: "Trikala Teller",
        category: "Spezialitäten vom Grill",
        price: "20,10",
        img: "",
        desc: "Gyros, 1 Souvlaki, 2 Leber, 1 Bifteki mit Reis, Zaziki und Salat",
    },
    {
        id: 48,
        title: "Schweinefilet",
        category: "Spezialitäten vom Grill",
        price: "19,10",
        img: "",
        desc: "Mit Käsesauce, Pommes Frites und Salat",
    },
    {
        id: 49,
        title: "Spezial Bifteki",
        category: "Spezialitäten vom Grill",
        price: "17,60",
        img: "",
        desc: "Hacksteak mit Schafskäse gefüllt, mit Reis und Salat",
    },
    {
        id: 50,
        title: "Syrtaki Teller",
        category: "Spezialitäten vom Grill",
        price: "18,10",
        img: "",
        desc: "1 Souvlaki, 1 Schweinesteak, Gyros mit Reis, Zaziki und Salat",
    },
    {
        id: 52,
        title: "Kreta Platte",
        category: "Kombinationen für mehrere Personen",
        price: "44,10",
        img: "",
        desc: "Für 2 Personen | Gyros, 2 Souvlaki, 2 Leber, 2 Bifteki, 2 Lammkotelett mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 53,
        title: "Kreta Platte",
        category: "Kombinationen für mehrere Personen",
        price: "66,40",
        img: "",
        desc: "Für 3 Personen | Gyros, 3 Souvlaki, 3 Leber, 3 Bifteki, 3 Lammkotelett mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 54,
        title: "Kreta Platte",
        category: "Kombinationen für mehrere Personen",
        price: "86,20",
        img: "",
        desc: "Für 4 Personen | Gyros, 4 Souvlaki, 4 Leber, 4 Bifteki, 4 Lammkotelett mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 55,
        title: "Rhodos Platte",
        category: "Kombinationen für mehrere Personen",
        price: "48,30",
        img: "",
        desc: "Für 2 Personen | 2x 100g Rumpsteak, 2 Lammkotelett, 2 Schweinesteaks, 2 Putensteaks mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 56,
        title: "Rhodos Platte",
        category: "Kombinationen für mehrere Personen",
        price: "72,70",
        img: "",
        desc: "Für 3 Personen | 3x 100g Rumpsteak, 3 Lammkotelett, 3 Schweinesteaks, 3 Putensteaks mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 57,
        title: "Rhodos Platte",
        category: "Kombinationen für mehrere Personen",
        price: "97,60",
        img: "",
        desc: "Für 4 Personen | 4x 100g Rumpsteak, 4 Lammkotelett, 4 Schweinesteaks, 4 Putensteaks mit Reis, Pommes Frites, Zaziki und Salat",
    },
    {
        id: 58,
        title: "Rumpsteak",
        category: "Steaks vom Rind",
        price: "19,90",
        img: "",
        desc: "200g Steak mit Röstzwiebeln, Pommes Frites und Salat",
    },
    {
        id: 59,
        title: "Pfeffer-Rumpsteak",
        category: "Steaks vom Rind",
        price: "20,80",
        img: "",
        desc: "250g Steak mit Pfeffersauce, Pommes Frites und Salat",
    },
    {
        id: 61,
        title: "Souvlaki",
        category: "Kinder- und Seniorenteller",
        price: "11,00",
        img: "",
        desc: "Schweinefleischspieß mit Pommes Frites und Salat",
    },
    {
        id: 62,
        title: "Gyros",
        category: "Kinder- und Seniorenteller",
        price: "11,00",
        img: "",
        desc: "Mit Pommes Frites und Salat",
    },
    {
        id: 63,
        title: "Bifteki",
        category: "Kinder- und Seniorenteller",
        price: "11,00",
        img: "",
        desc: "2 Hacksteaks mit Pommes Frites und Salat",
    },
    {
        id: 64,
        title: "Wiener Schnitzel Junior",
        category: "Kinder- und Seniorenteller",
        price: "11,00",
        img: "",
        desc: "Mit Pommes Frites und Salat",
    },
    {
        id: 66,
        title: "Lammkotelett",
        category: "Lammspezialitäten vom Grill",
        price: "21,40",
        img: "",
        desc: "Mit Reis und Salat",
    },
    {
        id: 67,
        title: "Lammfilet",
        category: "Lammspezialitäten vom Grill",
        price: "22,60",
        img: "",
        desc: "Mit Knoblauchsauce, Bratkartoffeln, dicke weiße Bohnen und Salat",
    },
    {
        id: 68,
        title: "Jägerschnitzel",
        category: "Schnitzel-Gerichte",
        price: "12,60",
        img: "",
        desc: "Mit Pommes Frites und Salat",
    },
    {
        id: 69,
        title: "Wiener Schnitzel",
        category: "Schnitzel-Gerichte",
        price: "11,90",
        img: "",
        desc: "Vom Schwein mit Pommes Frites und Salat",
    },
    {
        id: 70,
        title: "Rahmschnitzel",
        category: "Schnitzel-Gerichte",
        price: "12,60",
        img: "",
        desc: "Mit frischen Champignons, Rahmsoße, Pommes Frites und Salat",
    },
    {
        id: 72,
        title: "Lachsfilet",
        category: "Fischgerichte aus der Pfanne",
        price: "19,60",
        img: "",
        desc: "Gegrillter Lachs mit Butterreis, Sauce Bernaise und Salat",
    },
    {
        id: 73,
        title: "Zanderfilet",
        category: "Fischgerichte aus der Pfanne",
        price: "18,40",
        img: "",
        desc: "Mit Fischsoße, Pommes Frites und Salat",
    },
    {
        id: 74,
        title: "Kalamares",
        category: "Fischgerichte aus der Pfanne",
        price: "17,90",
        img: "",
        desc: "Mit Gemüse, Zaziki und Salat",
    },
    {
        id: 75,
        title: "Gorgona Topf",
        category: "Fischgerichte aus der Pfanne",
        price: "19,60",
        img: "",
        desc: "Fisch mit pikanter Knoblauchsoße überbacken, Fischsoße, Pommes Frites und Salat",
    },
    {
        id: 76,
        title: "Scampi",
        category: "Fischgerichte aus der Pfanne",
        price: "21,60",
        img: "",
        desc: "Mit Tarama(Kaviarcreme) und Salat",
    },
    {
        id: 77,
        title: "Fischteller",
        category: "Fischgerichte aus der Pfanne",
        price: "22,60",
        img: "",
        desc: "Für 1 Person | Kalamares, 1 Seezunge, 2 Scampis mit Fischsoße, Pommes Frites und Salat",
    },
    {
        id: 78,
        title: "Fischteller",
        category: "Fischgerichte aus der Pfanne",
        price: "45,20",
        img: "",
        desc: "Für 2 Personen | Kalamares, 2 Seezunge, 4 Scampis mit Fischsoße, Pommes Frites und Salat",
    },
    {
        id: 79,
        title: "Tilapia-Filet",
        category: "Fischgerichte aus der Pfanne",
        price: "18,40",
        img: "",
        desc: "Mit Fischsoße, Pommes Frites und Salat",
    },
    {
        id: 140,
        title: "Gegrillte Dorade",
        category: "Fischgerichte aus der Pfanne",
        price: "22,90",
        img: "",
        desc: "Mit Fischsoße, Pommes Frites und gemischtem Salat",
    },
    {
        id: 80,
        title: "Musaka",
        category: "Spezialitäten des Hauses",
        price: "17,60",
        img: "",
        desc: "Auberginen-Kartoffel-Hackfleischauflauf mit Bechamel-Creme überzogen und Salat",
    },
    {
        id: 81,
        title: "Pastizio",
        category: "Spezialitäten des Hauses",
        price: "17,30",
        img: "",
        desc: "Griechischer Nudelauflauf mit Hackfleisch mit Bechamel-Creme überzogen und Salat",
    },
    {
        id: 82,
        title: "Suzukaki",
        category: "Spezialitäten des Hauses",
        price: "17,90",
        img: "",
        desc: "Hackfleischröllchen in Tomatensauce mit Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 83,
        title: "Mykonos-Steak",
        category: "Spezialitäten des Hauses",
        price: "17,90",
        img: "",
        desc: "Steak mit Ananas und Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 84,
        title: "Gyros-Topf",
        category: "Spezialitäten des Hauses",
        price: "18,90",
        img: "",
        desc: "Mit Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 85,
        title: "Schweinesteak pikant",
        category: "Spezialitäten des Hauses",
        price: "18,40",
        img: "",
        desc: "Mit Knoblauchsauce und Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 86,
        title: "Filetspitzen",
        category: "Spezialitäten des Hauses",
        price: "18,90",
        img: "",
        desc: "Vom Schwein, in Rahmsauce, frische Champignons, mit Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 88,
        title: "Putensteak",
        category: "Geflügel",
        price: "15,20",
        img: "",
        desc: "Mit Sauce Bernaise, Pommes Frites und Salat",
    },
    {
        id: 89,
        title: "Putenschnitzel",
        category: "Geflügel",
        price: "15,20",
        img: "",
        desc: "Mit Sauce Bernaise, Pommes Frites und Salat",
    },
    {
        id: 90,
        title: "Hähnchenbrustfilet",
        category: "Geflügel",
        price: "18,30",
        img: "",
        desc: "Mit Rahmsoße und Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 93,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Auf Langkornnudeln mit Käse überbacken in Fleischsauce",
    },
    {
        id: 94,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit Spaghetti in Fleischsauce",
    },
    {
        id: 95,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit grünen Bohnen in Fleischsauce",
    },
    {
        id: 96,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit Auberginen in Fleischsauce",
    },
    {
        id: 97,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit Bamies(Ocraschotengemüse) in Fleischsauce",
    },
    {
        id: 98,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit gemischtem Gemüse in Fleischsauce",
    },
    {
        id: 99,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Mit dicken weißen Bohnen in Fleischsauce",
    },
    {
        id: 100,
        title: "Lammfleisch",
        category: "Aus dem Backofen",
        price: "17,90",
        img: "",
        desc: "Stifado mit geschmorten Zwiebeln in Fleischsauce",
    },
    {
        id: 107,
        title: "Turlu",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "gemischtes Gemüse",
    },
    {
        id: 108,
        title: "Gigandes",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "dicke weiße Bohnen mit Fleischsoße",
    },
    {
        id: 109,
        title: "Bamies",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Ocraschotengemüse",
    },
    {
        id: 110,
        title: "Grüne Bohnen",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Mit Brot",
    },
    {
        id: 111,
        title: "Stifado",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Mit geschmorten Zwiebeln in Sauce",
    },
    {
        id: 112,
        title: "Spaghetti",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Mit Fleischsauce",
    },
    {
        id: 113,
        title: "Spaghetti",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Mit Schafskäse",
    },
    {
        id: 114,
        title: "Kritharaki",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Langkornnudeln mit Fleischsauce",
    },
    {
        id: 115,
        title: "Kritharaki",
        category: "Diverse Kleinigkeiten",
        price: "10,00",
        img: "",
        desc: "Langkornnudeln mit Schafskäse",
    },
    {
        id: 502,
        title: "Bifteki",
        category: "Vom Grill",
        price: "14,80",
        img: "",
        desc: "3 gegrillte Hacksteaks in pikanter Sauce mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 503,
        title: "Ikarus Teller",
        category: "Vom Grill",
        price: "15,20",
        img: "",
        desc: "Putensteak in pikanter Sauce mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 504,
        title: "Gefülltes Hacksteak",
        category: "Vom Grill",
        price: "18,70",
        img: "",
        desc: "Mit Schafskäse, gegrillte Leber mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 505,
        title: "Schweinefilet",
        category: "Vom Grill",
        price: "18,90",
        img: "",
        desc: "Mit Bifteki, pikanter Sauce, Pommes Frites und Salat",
    },
    {
        id: 506,
        title: "Schweinefiletspieß",
        category: "Vom Grill",
        price: "19,50",
        img: "",
        desc: "Mit Schaftskäse gefüllt in pikanter Sauce mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 515,
        title: "Sparta Teller",
        category: "Vom Grill",
        price: "18,60",
        img: "",
        desc: "Gegrilltes Gyros und Kalamares aus der Pfanne mit Zaziki mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 517,
        title: "Lamm Kokinisto",
        category: "Aus dem Backofen",
        price: "19,80",
        img: "",
        desc: "Lammkeule mit Gemüse Schafskäse mit Käse überbacken, Pommes Frites und Salat",
    },
    {
        id: 507,
        title: "Garides Saganaki",
        category: "Aus der Pfanne",
        price: "18,20",
        img: "",
        desc: "Scampis in Paprikasauce mit Schafskäse vefeinert mit Reis oder Pommes Frites und Salat",
    },
    {
        id: 511,
        title: "Forelle",
        category: "Aus der Pfanne",
        price: "15,80",
        img: "",
        desc: "Mit Reis und Salat",
    },
    {
        id: 512,
        title: "Gyros und Spaghetti",
        category: "Aus der Pfanne",
        price: "14,90",
        img: "",
        desc: "Mit Metaxa Sauce (leicht pikant) und Salat",
    },
    {
        id: 513,
        title: "Hähnchenfilet Saganaki",
        category: "Aus der Pfanne",
        price: "17,90",
        img: "",
        desc: "Mit Paprikasauce und Schafskäse, Reis oder Pommes Frites und Salat",
    },
    {
        id: 514,
        title: "Delphi-Pfanne",
        category: "Aus der Pfanne",
        price: "17,90",
        img: "",
        desc: "Hähnchenbrustfilet mit Champignons in Senfsauce mit Reis oder Pommes Frites und Salat",
    },
    ]
export default menu